### ISSUE TITLE
line 156, in run     except Exception("model error!") as e: TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by TheMeIonGod** [iPERDance/iPERCore#126]
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\iperc\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\services\preprocess.py", line 44, in run
    device=device
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\tools\processors\preprocessors.py", line 116, in __init__
    device=device
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\tools\human_mattors\point_render_parser.py", line 11, in <module>
    from mmdet.apis import init_detector, inference_detector
ModuleNotFoundError: No module named 'mmdet'
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\services\preprocess.py", line 139, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\services\preprocess.py", line 213, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\services\options\process_info.py", line 167, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\services\options\process_info.py", line 260, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\iperc\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Admin\Desktop\iPERCore-main\iPERCore-main\iPERCore\services\preprocess.py", line 156, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...

Here is the command I used if that is the problem: 
python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 2 --output_dir "./results" --assets_dir "./assets" --model_id   "pew" --src_path   "path?=./assets/samples/sources/pew/pew.png,name?=pew" --ref_path   "path?=./assets/samples/references/orange.mp4,name?=orange,pose_fc?=300"

**Comment by Ariellsc** [comment]
I have met the same error, hava you solved it? thx
