### ISSUE TITLE
KeyError: 'cu111'

### ISSUE THREAD

**Issue by Qoes** [iPERDance/iPERCore#139]
I am trying to use CUDA 11.1 instead of 10.1 to use this but instead of setting thing sup, I get the error "KeyError: 'cu111'" and I'm not sure what to do.
Here is everything in the anaconda prompt pasted:

`
(base) C:\Users\vohnr>D:

(base) D:\>cd D:\Installations\Funny Fullbody Deepfake\iPERCore-main

(base) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>conda create -n iperc python=3.6.6
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: D:\Installations\Anaconda3\envs\iperc

  added / updated specs:
    - python=3.6.6

The following NEW packages will be INSTALLED:

  certifi            pkgs/main/win-64::certifi-2021.5.30-py36haa95532_0
  pip                pkgs/main/win-64::pip-21.2.2-py36haa95532_0
  python             pkgs/main/win-64::python-3.6.6-hea74fb7_0
  setuptools         pkgs/main/win-64::setuptools-58.0.4-py36haa95532_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py36h7fe50ca_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate iperc
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>conda activate iperc

(iperc) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>conda install pytorch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchvision==0.9.1+cu111
  - pytorch==1.8.1+cu111

Current channels:

  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

(iperc) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>python setup.py develop
Cuda version is 11.1
Traceback (most recent call last):
  File "setup.py", line 357, in <module>
    torch_torchvision_mmcv = platform_dependencies()
  File "setup.py", line 237, in platform_dependencies
    torch = get_torch_version(cuda_version_str, WINDOWS_PRECOMPILED_TORCH_CUDA_PAIRS, DEFAULT_WINDOWS_CUDA_TORCH)
  File "setup.py", line 207, in get_torch_version
    torch_version_str = default_torch_cuda_mapper[cuda_version_str]
KeyError: 'cu111'

(iperc) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>python setup.py develop
Cuda version is 11.1
Traceback (most recent call last):
  File "setup.py", line 357, in <module>
    torch_torchvision_mmcv = platform_dependencies()
  File "setup.py", line 237, in platform_dependencies
    torch = get_torch_version(cuda_version_str, WINDOWS_PRECOMPILED_TORCH_CUDA_PAIRS, DEFAULT_WINDOWS_CUDA_TORCH)
  File "setup.py", line 207, in get_torch_version
    torch_version_str = default_torch_cuda_mapper[cuda_version_str]
KeyError: 'cu111'

(iperc) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: D:\Installations\Anaconda3\envs\iperc

  added / updated specs:
    - cudatoolkit=11.1
    - pytorch
    - torchaudio
    - torchvision

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    lerc-3.0                   |       h0e60522_0         140 KB  conda-forge
    libdeflate-1.8             |       h8ffe710_0          61 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         202 KB

The following NEW packages will be INSTALLED:

  blas               conda-forge/win-64::blas-2.112-mkl
  blas-devel         conda-forge/win-64::blas-devel-3.9.0-12_win64_mkl
  cpuonly            pytorch/noarch::cpuonly-2.0-0
  cudatoolkit        conda-forge/win-64::cudatoolkit-11.1.1-heb2d755_9
  dataclasses        conda-forge/noarch::dataclasses-0.8-pyh787bdff_2
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_1
  intel-openmp       conda-forge/win-64::intel-openmp-2022.0.0-h57928b3_3663
  jbig               conda-forge/win-64::jbig-2.1-h8d14728_2003
  jpeg               conda-forge/win-64::jpeg-9d-h8ffe710_0
  lcms2              conda-forge/win-64::lcms2-2.12-h2a16943_0
  lerc               conda-forge/win-64::lerc-3.0-h0e60522_0
  libblas            conda-forge/win-64::libblas-3.9.0-12_win64_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-12_win64_mkl
  libdeflate         conda-forge/win-64::libdeflate-1.8-h8ffe710_0
  liblapack          conda-forge/win-64::liblapack-3.9.0-12_win64_mkl
  liblapacke         conda-forge/win-64::liblapacke-3.9.0-12_win64_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h1d00b33_2
  libtiff            conda-forge/win-64::libtiff-4.3.0-hd413186_2
  libuv              conda-forge/win-64::libuv-1.43.0-h8ffe710_0
  libzlib            conda-forge/win-64::libzlib-1.2.11-h8ffe710_1013
  lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  mkl                conda-forge/win-64::mkl-2021.4.0-h0e2418a_729
  mkl-devel          conda-forge/win-64::mkl-devel-2021.4.0-h57928b3_730
  mkl-include        conda-forge/win-64::mkl-include-2021.4.0-h0e2418a_729
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  numpy              conda-forge/win-64::numpy-1.19.5-py36h4b40d73_2
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openjpeg           conda-forge/win-64::openjpeg-2.4.0-hb211442_1
  pillow             conda-forge/win-64::pillow-8.3.2-py36h10c25d6_0
  python_abi         conda-forge/win-64::python_abi-3.6-2_cp36m
  pytorch            pytorch/win-64::pytorch-1.10.1-py3.6_cpu_0
  pytorch-mutex      pytorch/noarch::pytorch-mutex-1.0-cpu
  tbb                conda-forge/win-64::tbb-2021.5.0-h2d74725_0
  tk                 conda-forge/win-64::tk-8.6.11-h8ffe710_1
  torchaudio         pytorch/win-64::torchaudio-0.10.1-py36_cpu
  torchvision        pytorch/win-64::torchvision-0.11.2-py36_cpu
  typing_extensions  conda-forge/noarch::typing_extensions-4.0.1-pyha770c72_0
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1
  zlib               conda-forge/win-64::zlib-1.2.11-h8ffe710_1013
  zstd               conda-forge/win-64::zstd-1.5.1-h6255e5f_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main::certifi-2021.5.30-py36haa9~ --> conda-forge::certifi-2021.5.30-py36ha15d459_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
libdeflate-1.8       | 61 KB     | ############################################################################ | 100%
lerc-3.0             | 140 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: - "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

done

(iperc) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>python setup.py develop
Cuda version is 11.1
Traceback (most recent call last):
  File "setup.py", line 357, in <module>
    torch_torchvision_mmcv = platform_dependencies()
  File "setup.py", line 237, in platform_dependencies
    torch = get_torch_version(cuda_version_str, WINDOWS_PRECOMPILED_TORCH_CUDA_PAIRS, DEFAULT_WINDOWS_CUDA_TORCH)
  File "setup.py", line 207, in get_torch_version
    torch_version_str = default_torch_cuda_mapper[cuda_version_str]
KeyError: 'cu111'

(iperc) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 2 --output_dir "./results" --assets_dir "./assets" --model_id   "test" --src_path   "path?=./assets/samples/sources/man/man.png,name?=man" --ref_path   "path?=./assets/samples/references/fortnite.mp4,name?=fortnite,pose_fc?=300"
Traceback (most recent call last):
  File "demo/motion_imitate.py", line 11, in <module>
    from iPERCore.services.options.options_setup import setup
ModuleNotFoundError: No module named 'iPERCore'

(iperc) D:\Installations\Funny Fullbody Deepfake\iPERCore-main>`

**Comment by purangparam** [comment]
you can fix in it setup.py
in terms of window, cu111 doesn't written in setup.py
so you open the setup.py and just add "cu111": "1.8.1" in DEFAULT_WINDOWS_CUDA_TORCH

Also you can add "1.8.1+cu111": {
        "torch": "https://download.pytorch.org/whl/cu102/torch-1.8.1-cp{PYTHON_VERSION}-cp{PYTHON_ABI_VERSION}-win_amd64.whl",
        "torchvision": "https://download.pytorch.org/whl/cu111/torchvision-0.9.1-cp{PYTHON_VERSION}-cp{PYTHON_ABI_VERSION}-win_amd64.whl",
        "mmcv-full": "1.2.0",
        "mmcv-dist": f"{MMCV_DIST}/cu111/torch1.8.1/index.html"
    }
    in WINDOWS_PRECOMPILED_TORCH_CUDA_PAIRS
