### ISSUE TITLE
Operation error 

### ISSUE THREAD

**Issue by masato-mouse** [iPERDance/iPERCore#158]
I try Run the trump case.
But it occur OSError: [Errno 95] Operation not supported.
Google colab connected.
And I confirmed file path.
But , it can't solve.

May I help you?

<Detail >
Maybe, it occur error by input file .

Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/iPERCore/iPERCore/services/preprocess.py", line 80, in run
    visual=True,
  File "/content/drive/MyDrive/Colab Notebooks/iPERCore/iPERCore/tools/processors/base_preprocessor.py", line 74, in execute
    src_img_dir = process_utils.format_imgs_dir(input_path, processed_info["src_img_dir"])
  File "/content/drive/MyDrive/Colab Notebooks/iPERCore/iPERCore/tools/processors/process_utils.py", line 32, in format_imgs_dir
    os.symlink(osp.abspath(src_path), osp.abspath(dst_path))
OSError: [Errno 95] Operation not supported: '/content/drive/MyDrive/Colab Notebooks/iPERCore/assets/samples/sources/wangyibo_2.jpg' -> '/content/drive/MyDrive/Colab Notebooks/iPERCore/results/primitives/processed/orig_images/wangyibo_2.jpg'

**Comment by masato-mouse** [comment]
Sorry, It solved
