### ISSUE TITLE
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

### ISSUE THREAD

**Issue by molo32** [iPERDance/iPERCore#17]
I try to generate imitation with a custom video but it gives this error.

```
"/content/iPERCore/assets/samples/references/anai.mp4,name?=ana,pose_fc?=00"
/content/iPERCore/iPERCore/services/options/meta_info.py:170: UserWarning: /content/iPERCore/assets/samples/references/anai.mp4 has no key, and it is the first item, here we will set it as the `path`.
  warnings.warn(f"{kv_pair} has no key, and it is the first item, "
ffmpeg -y -i /content/iPERCore/assets/samples/references/anai.mp4 -ab 160k -ac 2 -ar 44100 -vn ./results/primitives/ana/processed/audio.mp3 -loglevel quiet
ffprobe -v error -select_streams v -of default=noprint_wrappers=1:nokey=1 -show_entries stream=r_frame_rate /content/iPERCore/assets/samples/references/anai.mp4
	Pre-processing: start...
----------------------MetaProcess----------------------
meta_input:
	path: /content/iPERCore/assets/samples/sources/65142266_019_c583.jpg
	bg_path: 
	name: 
primitives_dir: ./results/primitives/
processed_dir: ./results/primitives/processed
vid_info_path: ./results/primitives/processed/vid_info.pkl
-------------------------------------------------------
	has_run_detector: True
	has_run_cropper: True
	has_run_3dpose: True
	has_find_front: True
	has_run_parser: True
	has_run_inpaintor: True
	has_run_deform: True
	has_finished: True
----------------------MetaProcess----------------------
meta_input:
	path: /content/iPERCore/assets/samples/references/anai.mp4
	bg_path: 
	name: ana
	audio: ./results/primitives/ana/processed/audio.mp3
	fps: 30.0
	pose_fc: 0.0
	cam_fc: 100
primitives_dir: ./results/primitives/ana
processed_dir: ./results/primitives/ana/processed
vid_info_path: ./results/primitives/ana/processed/vid_info.pkl
-------------------------------------------------------
/content/iPERCore/assets/samples/references/anai.mp4 Writing frames to file
ffmpeg -i /content/iPERCore/assets/samples/references/anai.mp4 -start_number 0 ./results/primitives/ana/processed/orig_images/frame_%08d.png
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/iPERCore/assets/samples/references/anai.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2020-10-17T06:58:39.000000Z
  Duration: 00:00:15.07, start: 0.000000, bitrate: 577 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 206x222 [SAR 1:1 DAR 103:111], 447 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2020-10-17T06:58:40.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2020-10-17T06:58:40.000000Z
      handler_name    : Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to './results/primitives/ana/processed/orig_images/frame_%08d.png':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf57.83.100
    Stream #0:0(eng): Video: png, rgb24, 206x222 [SAR 1:1 DAR 103:111], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2020-10-17T06:58:40.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : Lavc57.107.100 png
frame=  451 fps=364 q=-0.0 Lsize=N/A time=00:00:15.03 bitrate=N/A speed=12.1x    
video:25552kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
	1.1 Preprocessing, running Preprocessor to detect the human boxes of ./results/primitives/ana/processed/orig_images...
100% 451/451 [00:31<00:00, 14.44it/s]
	1.1 Preprocessing, finish detect the human boxes of ./results/primitives/ana/processed/orig_images ...
	1.2 Preprocessing, cropping all images in ./results/primitives/ana/processed/orig_images by estimated boxes ...
451it [00:04, 109.55it/s]
	1.2 Preprocessing, finish crop the human by boxes, and save them in ./results/primitives/ana/processed/images ...
	1.3 Preprocessing, running Preprocessor to 3D pose estimation of all images in./results/primitives/ana/processed/images ...
100% 15/15 [00:10<00:00,  1.38it/s]
	1.3 Preprocessing, finish 3D pose estimation successfully ....
Preprocessor has finished...
		Pre-processing: digital deformation start...
		Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2. 
	Pre-processing: successfully...
Step 2: running personalization on
Step 2: personalization done, saved in ./results/models/donald_trump_2/personalized.pth...
Step 3: running imitator.
Network AttLWB-SPADE was created
Loading net from ./results/models/donald_trump_2/personalized.pth
Model Imitator was created
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3385: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/iPERCore/iPERCore/services/run_imitator.py", line 180, in <module>
    run_imitator(opt=OPT)
  File "/content/iPERCore/iPERCore/services/run_imitator.py", line 169, in run_imitator
    all_meta_outputs = imitate(opt)
  File "/content/iPERCore/iPERCore/services/run_imitator.py", line 135, in imitate
    ref_smpls = temporal_smooth_smpls(ref_smpls, pose_fc=meta_output.pose_fc, cam_fc=meta_output.cam_fc)
  File "/content/iPERCore/iPERCore/tools/utils/signals/smooth.py", line 210, in temporal_smooth_smpls
    ref_rot6d = get_smooth_params(ref_rot6d, fc=pose_fc)
  File "/content/iPERCore/iPERCore/tools/utils/signals/smooth.py", line 90, in get_smooth_params
    b, a = signal.butter(n, w, 'low')
  File "/usr/local/lib/python3.6/dist-packages/scipy/signal/filter_design.py", line 2894, in butter
    output=output, ftype='butter', fs=fs)
  File "/usr/local/lib/python3.6/dist-packages/scipy/signal/filter_design.py", line 2367, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1
```

**Comment by piaozhx** [comment]
Can you provide this video for debuging？

**Comment by StevenLiuWen** [comment]
Hi, @molo32, it seems that you have set `pose_fc = 00` in **/content/iPERCore/assets/samples/references/anai.mp4,name?=ana,pose_fc?=00**. The pose_fc must be > 0.
