### ISSUE TITLE
pip install git+https://github.com/open-mmlab/mmediting@d4086aaf8a36ae830f1714aad585900d24ad1156 安装报错

### ISSUE THREAD

**Issue by yuyusmile** [iPERDance/iPERCore#170]
pip install git+https://github.com/open-mmlab/mmediting@d4086aaf8a36ae830f1714aad585900d24ad1156 
Collecting git+https://github.com/open-mmlab/mmediting@d4086aaf8a36ae830f1714aad585900d24ad1156
  Cloning https://github.com/open-mmlab/mmediting (to revision d4086aaf8a36ae830f1714aad585900d24ad1156) to /tmp/pip-req-build-zt8mbeln
  Running command git clone --filter=blob:none -q https://github.com/open-mmlab/mmediting /tmp/pip-req-build-zt8mbeln
  Running command git rev-parse -q --verify 'sha^d4086aaf8a36ae830f1714aad585900d24ad1156'
  Running command git fetch -q https://github.com/open-mmlab/mmediting d4086aaf8a36ae830f1714aad585900d24ad1156
  Running command git checkout -q d4086aaf8a36ae830f1714aad585900d24ad1156
  Resolved https://github.com/open-mmlab/mmediting to commit d4086aaf8a36ae830f1714aad585900d24ad1156
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/banana/anaconda3/envs/gan/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zt8mbeln/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zt8mbeln/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fnd5mssr
       cwd: /tmp/pip-req-build-zt8mbeln/
  Complete output (23 lines):
  Couldn't find index page for 'pytest-runner' (maybe misspelled?)
  No local packages or working download links found for pytest-runner
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-zt8mbeln/setup.py", line 169, in <module>
      zip_safe=False)
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/site-packages/setuptools/dist.py", line 335, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
      replace_conflicting=True,
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
      replace_conflicting=replace_conflicting
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
      return self.obtain(req, installer)
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
      return installer(requirement)
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
      return cmd.easy_install(req)
    File "/home/banana/anaconda3/envs/gan/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
      raise DistutilsError(msg)
  distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

**Comment by ximply** [comment]
先安装pytest-runner试下
