### ISSUE TITLE
ModuleNotFoundError: No module named 'neural_renderer'

### ISSUE THREAD

**Issue by alivequietly** [iPERDance/iPERCore#21]
D:\Candhome\计算机视觉学习迁移\iPERCore-main>python demo/motion_imitate.py --gpu_ids 0  --image_size 512  --num_source 2  --output_dir "./results"  --assets_dir "./assets"   --model_id   "donald_trump_2"  --src_path   "path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2"  --ref_path   "path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300"
Traceback (most recent call last):
  File "demo/motion_imitate.py", line 10, in <module>
    from iPERCore.services.run_imitator import run_imitator
  File "d:\candhome\计算机视觉学习迁移\ipercore-main\iPERCore\services\run_imitator.py", line 4, in <module>
    from iPERCore.models import ModelsFactory
  File "d:\candhome\计算机视觉学习迁移\ipercore-main\iPERCore\models\__init__.py", line 2, in <module>
    from .flowcomposition import FlowComposition
  File "d:\candhome\计算机视觉学习迁移\ipercore-main\iPERCore\models\flowcomposition.py", line 7, in <module>
    from iPERCore.tools.human_digitalizer.renders import SMPLRenderer
  File "d:\candhome\计算机视觉学习迁移\ipercore-main\iPERCore\tools\human_digitalizer\renders\__init__.py", line 1, in <module>
    from .nmr import SMPLRenderer
  File "d:\candhome\计算机视觉学习迁移\ipercore-main\iPERCore\tools\human_digitalizer\renders\nmr.py", line 6, in <module>
    import neural_renderer as nr
ModuleNotFoundError: No module named 'neural_renderer'

**Comment by bigboss97** [comment]
Having same issue here. What did I miss?

(venv) PS E:\bin\iPERCore-main> python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 2 --output_dir "./results" --assets_dir "./assets" --model_id   "donald_trump_2" --src_path   "path?=./assets/samples1/sources/donald_trump_2/00000.PNG,name?=donald_trump_2" --ref_path   "path?=./assets/samples1/references/akun_2.mp4,name?=akun_2,pose_fc?=300"
Traceback (most recent call last):
  File "demo/motion_imitate.py", line 10, in <module>
    from iPERCore.services.run_imitator import run_imitator
  File "e:\bin\ipercore-main\iPERCore\services\run_imitator.py", line 4, in <module>
    from iPERCore.models import ModelsFactory
  File "e:\bin\ipercore-main\iPERCore\models\__init__.py", line 2, in <module>
    from .flowcomposition import FlowComposition
  File "e:\bin\ipercore-main\iPERCore\models\flowcomposition.py", line 7, in <module>
    from iPERCore.tools.human_digitalizer.renders import SMPLRenderer
  File "e:\bin\ipercore-main\iPERCore\tools\human_digitalizer\renders\__init__.py", line 1, in <module>
    from .nmr import SMPLRenderer
  File "e:\bin\ipercore-main\iPERCore\tools\human_digitalizer\renders\nmr.py", line 6, in <module>
    import neural_renderer as nr
ModuleNotFoundError: No module named 'neural_renderer'

**Comment by piaozhx** [comment]
refer #12

**Comment by anguoKuang** [comment]
需要安装这个库，但是我在安装过程中出现了错误，这个库没怎么维护了
