### ISSUE TITLE
Reference or source? AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by bigboss97** [iPERDance/iPERCore#40]
Does following error mean that the "main actor" can't be located in the reference video?

```
-------------------------------------------------------
	1.1 Preprocessing, running Preprocessor to detect the human boxes of ./results/primitives/mom/processed/orig_images...
100% 2/2 [00:00<00:00,  3.69it/s]
	1.1 Preprocessing, finish detect the human boxes of ./results/primitives/mom/processed/orig_images ...
	1.2 Preprocessing, cropping all images in ./results/primitives/mom/processed/orig_images by estimated boxes ...
2it [00:00,  5.47it/s]
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "/content/iPERCore/iPERCore/services/preprocess.py", line 77, in run
    visual=True,
  File "/content/iPERCore/iPERCore/tools/processors/base_preprocessor.py", line 88, in execute
    self._execute_crop_img(processed_info, crop_size, bg_path, num_workers=num_workers)
  File "/content/iPERCore/iPERCore/tools/processors/base_preprocessor.py", line 229, in _execute_crop_img
    crop_info = process_utils.process_crop_img(bg_img, fmt_active_boxes, crop_size)
  File "/content/iPERCore/iPERCore/tools/processors/process_utils.py", line 209, in process_crop_img
    x0, y0, x1, y1 = get_approximate_square_crop_boxes(orig_img.shape[0:2], active_bbox)
AttributeError: 'NoneType' object has no attribute 'shape'
```
In this video, sometimes there's more than one dancer to be seen. Is this confusing the algorithm?
I have another video with more than one dancer to be seen and it worked.

**Comment by bigboss97** [comment]
Oops, it was the background image, file not found.
Sorry about that  :-)
