### ISSUE TITLE
运行motion_imitate.py报错？

### ISSUE THREAD

**Issue by anguoKuang** [iPERDance/iPERCore#46]
The path to the mixture prior "./assets/checkpoints/pose3d\gmm_08.pkl" does not exist, exiting!
		Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "A:\py_workspace\iPERCore-main3\iPERCore-main\iPERCore\services\preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "A:\py_workspace\iPERCore-main3\iPERCore-main\iPERCore\services\preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "A:\py_workspace\iPERCore-main3\iPERCore-main\iPERCore\services\options\process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "A:\py_workspace\iPERCore-main3\iPERCore-main\iPERCore\services\options\process_info.py", line 237, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "A:\Anaconda\envs\IPERcore37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "A:\py_workspace\iPERCore-main3\iPERCore-main\iPERCore\services\preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
		Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2. 
	Pre-processing: failed...

Process finished with exit code 0

**Comment by piaozhx** [comment]
报错第一行就是问题所在:
```
The path to the mixture prior "./assets/checkpoints/pose3d\gmm_08.pkl" does not exist, exiting!
```
你检查一下这个文件为何不在了? 或许是因为你并没有在iPERCore文件夹路径下执行motion_imitate.py
