### ISSUE TITLE
FileNotFoundError: Cannot read cuda version file

### ISSUE THREAD

**Issue by Datadelete10426** [iPERDance/iPERCore#52]
PS E:\iPERCore> python setup.py develop
Traceback (most recent call last):
  File "E:\iPERCore\setup.py", line 257, in <module>
    torch_torchvision_mmcv = platform_dependencies()
  File "E:\iPERCore\setup.py", line 130, in platform_dependencies
    cuda_version = get_cuda_version()
  File "E:\iPERCore\setup.py", line 86, in get_cuda_version
    raise FileNotFoundError(f"Cannot read cuda version file {cuda_version_file}")
FileNotFoundError: Cannot read cuda version file C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\version.txt
到对应的目录下看也没有这个文件
这种是什么情况？换了CUDA版本也不行

**Comment by piaozhx** [comment]
@Datadelete10426 安装CUDA10.2试试

**Comment by anguoKuang** [comment]
> PS E:\iPERCore> python setup.py develop
> Traceback (most recent call last):
> File "E:\iPERCore\setup.py", line 257, in
> torch_torchvision_mmcv = platform_dependencies()
> File "E:\iPERCore\setup.py", line 130, in platform_dependencies
> cuda_version = get_cuda_version()
> File "E:\iPERCore\setup.py", line 86, in get_cuda_version
> raise FileNotFoundError(f"Cannot read cuda version file {cuda_version_file}")
> FileNotFoundError: Cannot read cuda version file C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\version.txt
> 到对应的目录下看也没有这个文件
> 这种是什么情况？换了CUDA版本也不行

这个也可以在对应的文件夹自己创建一个version.txt文件
一下是version文件里的内容：
![image](https://user-images.githubusercontent.com/35356618/103776840-ff9a7480-506a-11eb-8700-49bf8107cfa0.png)

**Comment by farisz14** [comment]
i have the same problem, even update to 10.2 it still cannot read cuda version file

**Comment by nerdyrodent** [comment]
I created the file "version.txt" myself and added text similar to the screenshot above.... though setup.py still won't complete.

I can install most of the dependencies manually with conda/pip:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch
conda install -c anaconda scikit-image tqdm visdom easydict toml
pip install opencv-python 
export CUDA_HOME=/usr/local/cuda
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
```
But this still leaves me with this to work around:
ModuleNotFoundError: No module named 'neural_renderer'
