### ISSUE TITLE
DLL load failed while importing load_textures: 找不到指定的模块

### ISSUE THREAD

**Issue by Datadelete10426** [iPERDance/iPERCore#53]
Traceback (most recent call last):
  File "demo/motion_imitate.py", line 10, in <module>
    from iPERCore.services.run_imitator import run_imitator
  File "e:\ipercore\iPERCore\services\run_imitator.py", line 4, in <module>
    from iPERCore.models import ModelsFactory
  File "e:\ipercore\iPERCore\models\__init__.py", line 2, in <module>
    from .flowcomposition import FlowComposition
  File "e:\ipercore\iPERCore\models\flowcomposition.py", line 7, in <module>
    from iPERCore.tools.human_digitalizer.renders import SMPLRenderer
  File "e:\ipercore\iPERCore\tools\human_digitalizer\renders\__init__.py", line 1, in <module>
    from .nmr import SMPLRenderer
  File "e:\ipercore\iPERCore\tools\human_digitalizer\renders\nmr.py", line 6, in <module>
    import neural_renderer as nr
  File "C:\Users\Not found\AppData\Local\Programs\Python\Python38\lib\site-packages\neural_renderer\__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "C:\Users\Not found\AppData\Local\Programs\Python\Python38\lib\site-packages\neural_renderer\load_obj.py", line 9, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: DLL load failed while importing load_textures: 找不到指定的模块。
环境：Win10+py3.8+CUDA10.2

**Comment by piaozhx** [comment]
Have you solved your problem?

**Comment by piaozhx** [comment]
refer https://github.com/iPERDance/iPERCore/issues/30#issuecomment-754573312

**Comment by piaozhx** [comment]
@Datadelete10426  I guess this problem was caused by the wrong version of MSVC (i.e. Visual Studio), I recommend you to install the latest Visual Studio 2019 and select the related module of C++.

**Comment by Datadelete10426** [comment]
> @Datadelete10426 I guess this problem was caused by the wrong version of MSVC (i.e. Visual Studio), I recommend you to install the latest Visual Studio 2019 and select the related module of C++.

![image](https://user-images.githubusercontent.com/60697024/103671694-35c9ec80-4fb6-11eb-9af7-1d77ab6bb044.png)
Already installed

**Comment by piaozhx** [comment]
Any error occurred during the compilation?

**Comment by piaozhx** [comment]
I notice that you do not use any virtual environment (multiple CUDA version and old pytorch may cause some compatibility issues). you can build a new virtuall environment (conda or venv) and try installing the latest version of iPERCore from stretch.

**Comment by piaozhx** [comment]
@Datadelete10426 Each time you install a new version of pytorch, you must reinstall the neural_renderer (because it is compiled by pytorch), maybe that's the problem.

**Comment by anguoKuang** [comment]
> Traceback (most recent call last):
> File "demo/motion_imitate.py", line 10, in
> from iPERCore.services.run_imitator import run_imitator
> File "e:\ipercore\iPERCore\services\run_imitator.py", line 4, in
> from iPERCore.models import ModelsFactory
> File "e:\ipercore\iPERCore\models__init__.py", line 2, in
> from .flowcomposition import FlowComposition
> File "e:\ipercore\iPERCore\models\flowcomposition.py", line 7, in
> from iPERCore.tools.human_digitalizer.renders import SMPLRenderer
> File "e:\ipercore\iPERCore\tools\human_digitalizer\renders__init__.py", line 1, in
> from .nmr import SMPLRenderer
> File "e:\ipercore\iPERCore\tools\human_digitalizer\renders\nmr.py", line 6, in
> import neural_renderer as nr
> File "C:\Users\Not found\AppData\Local\Programs\Python\Python38\lib\site-packages\neural_renderer__init__.py", line 3, in
> from .load_obj import load_obj
> File "C:\Users\Not found\AppData\Local\Programs\Python\Python38\lib\site-packages\neural_renderer\load_obj.py", line 9, in
> import neural_renderer.cuda.load_textures as load_textures_cuda
> ImportError: DLL load failed while importing load_textures: 找不到指定的模块。
> 环境：Win10+py3.8+CUDA10.2

检查一下是不是你的torch安装成了cpu的版本？
