### ISSUE TITLE
AssertionError: MMCV==1.1.5 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.How to solve this mistake

### ISSUE THREAD

**Issue by bumie7758258** [iPERDance/iPERCore#64]
These errors occur when running motion_imitate.py 

Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "D:\anaconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 43, in run
    device=device
  File "D:\iPERCore-main\iPERCore\tools\processors\preprocessors.py", line 127, in __init__
    device=device
  File "D:\iPERCore-main\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "D:\iPERCore-main\iPERCore\tools\human_mattors\point_render_parser.py", line 11, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "D:\anaconda3\envs\venv\lib\site-packages\mmdet\__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.1.5 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 138, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 212, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "D:\iPERCore-main\iPERCore\services\options\process_info.py", line 142, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "D:\iPERCore-main\iPERCore\services\options\process_info.py", line 235, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\iPERCore-main\iPERCore\services\preprocess.py", line 155, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...****

**Comment by piaozhx** [comment]
same with #62
