### ISSUE TITLE
Could not find a version that satisfies the requirement mmcv-full==1.2.0+torch1.6.0+cu102 

### ISSUE THREAD

**Issue by cloudweather** [iPERDance/iPERCore#7]
Hi, thank you for the amazing work. 
I am trying to run this on a Windows 10 system.
When I entered:
```
python setup.py
```

It produces:
```
C:\Users\anaconda3\envs\iPER\python.exe -m pip install mmcv-full==1.2.0+torch1.6.0+cu102 -f https://download.openmmlab.com/mmcv/dist/index.html
Looking in links: https://download.openmmlab.com/mmcv/dist/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full==1.2.0+torch1.6.0+cu102 (from versions: 1.1.5+torch1.4.0+cpu, 1.1.5+torch1.5.1+cpu, 1.1.5+torch1.6.0+cpu, 1.1.5+torch1.6.0+cu101, 1.1.5+torch1.6.0+cu102, 1.0rc0, 1.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.2.1)
ERROR: No matching distribution found for mmcv-full==1.2.0+torch1.6.0+cu102
```

How can I fix this? Thank you

**Comment by piaozhx** [comment]
The latest mmcv doesn't have a compiled windows version because of some compatibility issues. you can try compiling mmcv from source code (it could be a little hard).

**Comment by cloudweather** [comment]
Thank you for your response, do you mind giving me a bit more insights on how to build it from source?

**Comment by MaxGodTier** [comment]
@cloudweather You can find the docs for building from source here: https://mmcv.readthedocs.io/en/latest/build.html
However, it can be tricky, even after building the CUDA version with zero error messages and installing it, I would get a "No module named 'mmcv._ext'" during the inference, I still have to investigate what went wrong, it's weird because I could clearly see that module getting built during compilation and there were no problems detecting CUDA.
Anyway, I went the easy way and downloaded a prebuilt package for PyTorch 1.6 instead, I didn't have trouble using it even if the requirements asked for PyTorch 1.7: https://download.openmmlab.com/mmcv/dist/index.html
These are the packages that work:
./1.1.5/torch1.6.0/cu101/mmcv_full-1.1.5+torch1.6.0+cu101-cp36-cp36m-win_amd64.whl
./1.1.5/torch1.6.0/cu101/mmcv_full-1.1.5+torch1.6.0+cu101-cp37-cp37m-win_amd64.whl
./1.1.5/torch1.6.0/cu101/mmcv_full-1.1.5+torch1.6.0+cu101-cp38-cp38-win_amd64.whl
./1.1.5/torch1.6.0/cu102/mmcv_full-1.1.5+torch1.6.0+cu102-cp36-cp36m-win_amd64.whl
./1.1.5/torch1.6.0/cu102/mmcv_full-1.1.5+torch1.6.0+cu102-cp37-cp37m-win_amd64.whl
./1.1.5/torch1.6.0/cu102/mmcv_full-1.1.5+torch1.6.0+cu102-cp38-cp38-win_amd64.whl
On a last note, I had to change the way the paths are handled, they didn't work out of the box with my Windows 10 machine, had to do something like cwd = os.getcwd() and define an absolute path such as cwd + '/assets/etcetera'
Hope that helps.

**Comment by cloudweather** [comment]
That's some amazing pointers, thanks.

Would earlier MMCV versions theoretically work?

**Comment by cloudweather** [comment]
@MaxGodTier How exactly did you change the codes to define the paths? Do you mind to elaborate a bit more? Thank you!

**Comment by cloudweather** [comment]
Is this an error in `deploy.toml`?
https://github.com/iPERDance/iPERCore/blob/c6bc8d360a9c9027a3e64e9a4c72b3f06a5e81a1/assets/configs/deploy.toml#L115

on line 115 and 116
I think the file path is suppose to be:
```
ffmpeg_exe_path = "./assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe"
ffprobe_exe_path = "./assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe"
```

instead of 
```
ffmpeg_exe_path = "./asssets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe"
ffprobe_exe_path = "./asssets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe"
```

but after changing this it only slightly changed the error I got, which is:

```
G:\iPer\iPERCore>python demo/motion_imitate.py --image_size 512 --num_source 2 --output_dir "./results" --assets_dir "./assets" --model_id   "donald_trump_2" --src_path   "path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2" --ref_path   "path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300"
ffprobe -v error -select_streams v -of default=noprint_wrappers=1:nokey=1 -show_entries stream=r_frame_rate ./assets/samples/references/akun_2.mp4

------------ Options -------------
{'MAX_NUM_SOURCE': 8,
 'MultiMedia': {'ffmpeg': {'Linux': {'ffmpeg_exe_path': 'ffmpeg',
                                     'ffprobe_exe_path': 'ffprobe'},
                           'Windows': {'ffmpeg_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe',
                                       'ffprobe_exe_path': './assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe'},
                           'pix_fmt': 'yuv420p',
                           'vcodec': 'h264'},
                'image': {'caption': 'this is a fake video, synthesized by '
                                     'impersonator++',
                          'saved_name_format': 'pred_{:0>8}.png'}},
 'NUMBER_FACES': 13776,
 'NUMBER_VERTS': 6890,
 'Preprocess': {'BackgroundInpaintor': {'bg_replace': True,
                                        'cfg_path': './assets/configs/inpaintors/mmedit_inpainting.toml',
                                        'dilate_iter_num': 3,
                                        'dilate_kernel_size': 9,
                                        'name': 'mmedit_inpainting',
                                        'use_sr': True},
                'Cropper': {'ref_crop_factor': 3.0, 'src_crop_factor': 1.3},
                'Deformer': {'cloth_parse_ckpt_path': './assets/checkpoints/mattors/exp-schp-lip.pth'},
                'FrontInfo': {'NUM_CANDIDATE': 25, 'RENDER_SIZE': 256},
                'HumanMattors': {'cfg_path': './assets/configs/mattors/point_render+gca.toml',
                                 'dilate_iter_num': 7,
                                 'erode_iter_num': 2,
                                 'morph_kernel_size': 3,
                                 'name': 'point_render+gca'},
                'MAX_PER_GPU_PROCESS': 1,
                'Pose2dEstimator': {'cfg_path': './assets/configs/pose2d/openpose/body25.toml',
                                    'joint_type': 'OpenPose-Body-25',
                                    'name': 'openpose'},
                'Pose3dEstimator': {'batch_size': 32,
                                    'cfg_path': './assets/configs/pose3d/spin.toml',
                                    'name': 'spin',
                                    'num_workers': 4},
                'Pose3dRefiner': {'cfg_path': './assets/configs/pose3d/smplify.toml',
                                  'name': 'smplify',
                                  'use_lfbgs': True},
                'Tracker': {'tracker_name': 'max_box'},
                'estimate_boxes_first': True,
                'filter_invalid': True,
                'has_detector': True,
                'temporal': True,
                'use_smplify': True},
 'Train': {'D_adam_b1': 0.9,
           'D_adam_b2': 0.999,
           'G_adam_b1': 0.9,
           'G_adam_b2': 0.999,
           'aug_bg': False,
           'display_freq_s': 30,
           'face_factor': 1.0,
           'face_loss_path': './assets/checkpoints/losses/sphere20a_20171020.pth',
           'final_lr': 2e-06,
           'lambda_D_prob': 1.0,
           'lambda_face': 5.0,
           'lambda_mask': 5.0,
           'lambda_mask_smooth': 1.0,
           'lambda_rec': 10.0,
           'lambda_tsf': 10.0,
           'lr_D': 0.0001,
           'lr_G': 0.0001,
           'niters_or_epochs_decay': 0,
           'niters_or_epochs_no_decay': 100,
           'num_iters_validate': 1,
           'opti': 'Adam',
           'print_freq_s': 30,
           'save_latest_freq_s': 300,
           'tb_visual': False,
           'train_G_every_n_iterations': 1,
           'use_face': True,
           'use_vgg': 'VGG19',
           'vgg_loss_path': './assets/checkpoints/losses/vgg19-dcbb9e9d.pth'},
 'assets_dir': './assets',
 'batch_size': 1,
 'bg_ks': 11,
 'cam_strategy': 'smooth',
 'cfg_path': './assets\\configs\\deploy.toml',
 'digital_type': 'cloth_smpl_link',
 'dis_name': 'patch_global',
 'face_path': './assets/checkpoints/pose3d/smpl_faces.npy',
 'facial_path': './assets/checkpoints/pose3d/front_facial.json',
 'fim_enc_path': './assets/checkpoints/pose3d/mapper_fim_enc.txt',
 'front_path': './assets/checkpoints/pose3d/front_body.json',
 'ft_ks': 1,
 'gen_name': 'AttLWB-SPADE',
 'gpu_ids': '0',
 'head_path': './assets/checkpoints/pose3d/head.json',
 'image_size': 512,
 'intervals': 1,
 'ip': '',
 'load_epoch': -1,
 'load_path_D': 'None',
 'load_path_G': './assets/checkpoints/neural_renders/AttLWB-SPADE_id_G_2020-05-18.pth',
 'local_rank': 0,
 'map_name': 'uv_seg',
 'meta_data': {'checkpoints_dir': './results\\models\\donald_trump_2',
               'meta_ref': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001CBFFA3BA58>],
               'meta_src': [<iPERCore.services.options.meta_info.MetaProcess object at 0x000001CBFFA3BC88>],
               'opt_path': './results\\models\\donald_trump_2\\opts.txt',
               'personalized_ckpt_path': './results\\models\\donald_trump_2\\personalized.pth',
               'root_primitives_dir': './results\\primitives'},
 'model_id': 'donald_trump_2',
 'neural_render_cfg': {'Discriminator': {'bg_cond_nc': 4,
                                         'cond_nc': 6,
                                         'max_nf_mult': 8,
                                         'n_layers': 4,
                                         'name': 'patch_global',
                                         'ndf': 64,
                                         'norm_type': 'instance',
                                         'use_sigmoid': False},
                       'Generator': {'BGNet': {'cond_nc': 4,
                                               'n_res_block': 6,
                                               'norm_type': 'instance',
                                               'num_filters': [64,
                                                               128,
                                                               128,
                                                               256]},
                                     'SIDNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'None',
                                                'num_filters': [64, 128, 256]},
                                     'TSFNet': {'cond_nc': 6,
                                                'n_res_block': 6,
                                                'norm_type': 'instance',
                                                'num_filters': [64, 128, 256]},
                                     'name': 'AttLWB-SPADE'}},
 'neural_render_cfg_path': './assets/configs/neural_renders/AttLWB-SPADE.toml',
 'num_source': 1,
 'num_workers': 4,
 'only_vis': False,
 'output_dir': './results',
 'part_path': './assets/checkpoints/pose3d/smpl_part_info.json',
 'port': 0,
 'ref_path': 'path?=./assets/samples/references/akun_2.mp4,name?=akun_2,pose_fc?=300',
 'serial_batches': False,
 'share_bg': True,
 'smpl_model': './assets/checkpoints/pose3d/smpl_model.pkl',
 'smpl_model_hand': './assets/checkpoints/pose3d/smpl_model_with_hand_v2.pkl',
 'src_path': 'path?=./assets/samples/sources/donald_trump_2/00000.PNG,name?=donald_trump_2',
 'tb_visual': False,
 'temporal': False,
 'tex_size': 3,
 'time_step': 1,
 'train_name': 'LWGTrainer',
 'use_cudnn': False,
 'use_inpaintor': False,
 'uv_map_path': './assets/checkpoints/pose3d/mapper_uv.txt',
 'verbose': True}
-------------- End ----------------
        Pre-processing: start...
----------------------MetaProcess----------------------
meta_input:
        path: ./assets/samples/sources/donald_trump_2/00000.PNG
        bg_path:
        name: donald_trump_2
primitives_dir: ./results\primitives\donald_trump_2
processed_dir: ./results\primitives\donald_trump_2\processed
vid_info_path: ./results\primitives\donald_trump_2\processed\vid_info.pkl
-------------------------------------------------------
----------------------MetaProcess----------------------
meta_input:
        path: ./assets/samples/references/akun_2.mp4
        bg_path:
        name: akun_2
        audio: ./results\primitives\akun_2\processed\audio.mp3
        fps: 30.0
        pose_fc: 300.0
        cam_fc: 100
primitives_dir: ./results\primitives\akun_2
processed_dir: ./results\primitives\akun_2\processed
vid_info_path: ./results\primitives\akun_2\processed\vid_info.pkl
-------------------------------------------------------
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 77, in run
    visual=True,
  File "g:\iper\ipercore\iPERCore\tools\processors\base_preprocessor.py", line 72, in execute
    src_img_dir = process_utils.format_imgs_dir(input_path, processed_info["src_img_dir"])
  File "g:\iper\ipercore\iPERCore\tools\processors\process_utils.py", line 19, in format_imgs_dir
    os.symlink(osp.abspath(src_path), osp.abspath(dst_path))
OSError: symbolic link privilege not held

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\iPER\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 80, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "g:\iper\ipercore\iPERCore\services\options\process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "g:\iper\ipercore\iPERCore\services\options\process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\iPER\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...
```

**Comment by MaxGodTier** [comment]
@cloudweather as I already mentioned before, Windows didn't like relative paths, try using absolute paths.
Example:
cwd = os.getcwd()
ffmpeg_exe_path = cwd + "/assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe" #you want something like G:\iPer\iPERCore/assets/executables/ffmpeg-4.3.1-win64-static/bin/ffmpeg.exe

**Comment by StevenLiuWen** [comment]
hi, @cloudweather and @MaxGodTier, we have fixed the bug of installation in Windows, and try to clone the recent iPERCore-0.1.1.

**Comment by cloudweather** [comment]
Hi, I tried the updated version and got a slightly different error now.
Since setup.py cannot install the version of pytorch that was provided, I did this instead, for your information.


```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```
Maybe I should use CUDA 10.1?
```
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\iper\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 41, in run
    device=device
  File "g:\iper\ipercore\iPERCore\tools\processors\preprocessors.py", line 125, in __init__
    device=device
  File "g:\iper\ipercore\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "g:\iper\ipercore\iPERCore\tools\human_mattors\point_render_parser.py", line 16, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmdet\apis\__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmdet\apis\inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmcv\utils\ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\anaconda3\envs\iper\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "g:\iper\ipercore\iPERCore\services\options\process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "g:\iper\ipercore\iPERCore\services\options\process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\iper\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...
```

**Comment by StevenLiuWen** [comment]
> Hi, I tried the updated version and got a slightly different error now.
> Since setup.py cannot install the version of pytorch that was provided, I did this instead, for your information.
> 
> ```
> conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
> ```
> 
> Maybe I should use CUDA 10.1?
> 
> ```
> Process PreprocessConsumer_0:
> Traceback (most recent call last):
>   File "C:\Users\anaconda3\envs\iper\lib\multiprocessing\process.py", line 258, in _bootstrap
>     self.run()
>   File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 41, in run
>     device=device
>   File "g:\iper\ipercore\iPERCore\tools\processors\preprocessors.py", line 125, in __init__
>     device=device
>   File "g:\iper\ipercore\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
>     from .point_render_parser import PointRenderGCAMattor
>   File "g:\iper\ipercore\iPERCore\tools\human_mattors\point_render_parser.py", line 16, in <module>
>     from mmdet.apis import init_detector, inference_detector
>   File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmdet\apis\__init__.py", line 1, in <module>
>     from .inference import (async_inference_detector, inference_detector,
>   File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmdet\apis\inference.py", line 7, in <module>
>     from mmcv.ops import RoIPool
>   File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
>     from .bbox import bbox_overlaps
>   File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
>     ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
>   File "C:\Users\anaconda3\envs\iper\lib\site-packages\mmcv\utils\ext_loader.py", line 11, in load_ext
>     ext = importlib.import_module('mmcv.' + name)
>   File "C:\Users\anaconda3\envs\iper\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: DLL load failed: The specified procedure could not be found.
>                 Pre-processing: digital deformation start...
> Process HumanDigitalDeformConsumer_0:
> Traceback (most recent call last):
>   File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 136, in run
>     prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
>   File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
>     src_infos = process_info.convert_to_src_info(self.opt.num_source)
>   File "g:\iper\ipercore\iPERCore\services\options\process_info.py", line 140, in convert_to_src_info
>     src_infos = read_src_infos(self.vid_infos, num_source)
>   File "g:\iper\ipercore\iPERCore\services\options\process_info.py", line 233, in read_src_infos
>     pad_ids = np.random.choice(src_ids, need_pad)
>   File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
> ValueError: 'a' cannot be empty unless no samples are taken
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\anaconda3\envs\iper\lib\multiprocessing\process.py", line 258, in _bootstrap
>     self.run()
>   File "g:\iper\ipercore\iPERCore\services\preprocess.py", line 153, in run
>     except Exception("model error!") as e:
> TypeError: catching classes that do not inherit from BaseException is not allowed
>                 Pre-processing: digital deformation completed...
> the current number of sources are 1, while the pre-defined number of sources are 2.
>         Pre-processing: failed...
> ```

It seems that you have not installed the torch successfully, and thereby results in an error installation in MMCV.

What's your python version?

Could you install the torch successfully, if you run the following?
```shell
pip install https://download.pytorch.org/whl/cu102/torch-1.6.0-cp{PYTHON_VERSION}-cp{PYTHON_VERSION}-win_amd64.whl

```

Replace the PYTHON_VERSION with yours, such as 36, 37, 38. In my Windows, it is 38

**Comment by MaxGodTier** [comment]
@cloudweather you're installing the latest version of Pytorch (currently 1.7), you need the correct version of MMCV to go with it.
For instance, if I installed "mmcv_full-1.1.5+**torch1.6.0**+**cu102**-**cp37**-cp37m-win_amd64.whl" package, I'd need an environment with Pytorch 1.6.0, CUDA 10.2 and Python 3.7.

**Comment by cloudweather** [comment]
using 
```
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch
```
works, along with CUDA10.1

Thank you guys.
