### ISSUE TITLE
ModuleNotFoundError: No module named 'mmedit'

### ISSUE THREAD

**Issue by elegentbamboo** [iPERDance/iPERCore#74]
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "/home/lyl/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/services/preprocess.py", line 41, in run
    device=device
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/tools/processors/preprocessors.py", line 125, in __init__
    device=device
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/tools/human_mattors/__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/tools/human_mattors/point_render_parser.py", line 17, in <module>
    from mmedit.apis import init_model, matting_inference
ModuleNotFoundError: No module named 'mmedit'
		Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/services/preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/services/preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/services/options/process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/services/options/process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lyl/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lyl/软件/conda环境/iPERCore-main/iPERCore/services/preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
		Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2. 
	Pre-processing: failed...

Process finished with exit code 0

**Comment by Vladut41** [comment]
I have the same issue, did you solve it?
