### ISSUE TITLE
the current number of sources are 1, while the pre-defined number of sources are 2

### ISSUE THREAD

**Issue by Vladut41** [iPERDance/iPERCore#96]
I tried to change the number of sources but it doesn't work

**Comment by lyn444** [comment]
same issue here. anyone knows how to solve this?

**Comment by AndreyStille** [comment]
Faced same issue
Yesterday everythin was ok, changed nothing and today get this error
Have you find the solution?

**Comment by pymtl9082** [comment]
In my case, I noticed that a permission error below occured during making a symbolic link.
```
...

Traceback (most recent call last):
  File "./iPERCore/iPERCore/services/preprocess.py", line 66, in run
    processor.execute(
  File "./iPERCore/iPERCore/tools/processors/base_preprocessor.py", line 74, in execute
    src_img_dir = process_utils.format_imgs_dir(input_path, processed_info["src_img_dir"])
  File "./iPERCore/iPERCore/tools/processors/process_utils.py", line 32, in format_imgs_dir
    os.symlink(osp.abspath(src_path), osp.abspath(dst_path))
PermissionError: [Errno 1] Operation not permitted: './iPERCore/assets/samples/sources/donald_trump_2/00000.PNG' -> './iPERCore/results/primitives/donald_trump_2/processed/orig_images/00000.PNG'

...

the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...
```
It works after resolving the error.
